# Generated by Django 5.0.4 on 2024-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('colour', models.TextField()),
                ('country', models.TextField()),
                ('size', models.TextField()),
                ('status', models.BooleanField()),
                ('colour_name', models.TextField(default='WHITE')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
